#### Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset insklearn.datasets.


In [1]:
import seaborn as sns
from sklearn.datasets import load_iris
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = load_iris()
X = data['data']
y = data['target']

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [4]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5,algorithm='auto')

In [5]:
classifier.fit(X_train,y_train)
classifier.predict(X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

#### Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.


In [6]:
from sklearn.datasets import load_boston
data = load_boston()
X = data['data']
y = data['target']

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [8]:
from sklearn.neighbors import KNeighborsRegressor
regressor = KNeighborsRegressor(n_neighbors=5,algorithm='auto')

In [9]:
regressor.fit(X_train,y_train)
regressor.predict(X_test)

array([24.54, 29.34, 14.6 , 28.94, 17.44, 31.88, 20.58, 16.06, 18.02,
       21.18, 21.9 , 21.36, 12.28, 20.56, 23.7 , 21.74, 21.18, 14.06,
       33.72, 10.6 , 25.86, 29.34, 19.7 , 21.08, 18.88, 23.16, 21.88,
       12.34, 21.9 , 21.18, 22.68, 23.14, 10.3 , 30.04, 17.54, 21.12,
       21.66, 22.92, 22.52, 29.08, 21.18, 27.98, 38.82, 22.4 , 24.84,
       12.6 , 19.7 , 28.94, 19.8 , 22.22, 22.44, 34.7 , 22.04, 21.18,
       29.72, 21.38, 12.5 , 35.04, 21.82, 20.6 , 25.3 , 38.82, 28.68,
       16.26, 30.46, 24.24, 12.24, 25.3 , 35.04, 12.34, 23.94, 22.52,
       14.82, 30.38, 20.56,  8.98, 19.68, 38.82, 10.94, 15.04, 22.4 ,
       15.96, 26.3 , 12.24, 22.02, 34.  , 14.16, 22.58, 26.04, 17.86,
       24.5 , 15.22, 17.48, 21.76, 24.76, 17.86, 30.16, 10.76, 10.76,
       11.92, 21.82, 20.56, 23.16, 21.28, 22.22, 10.88, 23.96, 24.56,
       26.74, 26.3 ,  9.98, 15.74, 23.46, 33.72, 33.46, 15.22, 27.9 ,
       17.2 , 22.76, 22.44, 24.78, 31.62,  9.78, 18.74, 24.38, 23.28,
       28.28, 24.22,

#### Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.


In [10]:
from sklearn.model_selection import GridSearchCV
params = {'n_neighbors' :[1,2,3,4,5,6,7,8,9,10]}
classifier = GridSearchCV(KNeighborsRegressor(),param_grid = params,cv = 5)

In [11]:
classifier.fit(X_train,y_train)
classifier.best_params_

{'n_neighbors': 3}

#### Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets.

In [12]:
from sklearn.datasets import load_boston
data = load_boston()
X = data['data']
y = data['target']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train_scaled

array([[ 0.89624872, -0.51060139,  0.98278223, ...,  0.86442095,
         0.24040357,  0.77155612],
       [-0.34895881, -0.51060139, -0.44867555, ...,  1.22118698,
         0.20852839,  0.32248963],
       [-0.41764058,  0.03413008, -0.48748013, ..., -1.36536677,
         0.43481957,  0.92775316],
       ...,
       [-0.43451148,  2.97567999, -1.32968321, ..., -0.56264319,
         0.36745216, -0.90756208],
       [ 1.01703049, -0.51060139,  0.98278223, ...,  0.86442095,
        -2.80977992,  1.50233514],
       [-0.40667333, -0.51060139, -0.38831288, ...,  1.17659123,
        -3.25117205, -0.26046005]])

In [14]:
from sklearn.neighbors import KNeighborsRegressor
regressor = KNeighborsRegressor(n_neighbors=5,algorithm='auto')
regressor.fit(X_train,y_train)
regressor.predict(X_test)

array([24.54, 29.34, 14.6 , 28.94, 17.44, 31.88, 20.58, 16.06, 18.02,
       21.18, 21.9 , 21.36, 12.28, 20.56, 23.7 , 21.74, 21.18, 14.06,
       33.72, 10.6 , 25.86, 29.34, 19.7 , 21.08, 18.88, 23.16, 21.88,
       12.34, 21.9 , 21.18, 22.68, 23.14, 10.3 , 30.04, 17.54, 21.12,
       21.66, 22.92, 22.52, 29.08, 21.18, 27.98, 38.82, 22.4 , 24.84,
       12.6 , 19.7 , 28.94, 19.8 , 22.22, 22.44, 34.7 , 22.04, 21.18,
       29.72, 21.38, 12.5 , 35.04, 21.82, 20.6 , 25.3 , 38.82, 28.68,
       16.26, 30.46, 24.24, 12.24, 25.3 , 35.04, 12.34, 23.94, 22.52,
       14.82, 30.38, 20.56,  8.98, 19.68, 38.82, 10.94, 15.04, 22.4 ,
       15.96, 26.3 , 12.24, 22.02, 34.  , 14.16, 22.58, 26.04, 17.86,
       24.5 , 15.22, 17.48, 21.76, 24.76, 17.86, 30.16, 10.76, 10.76,
       11.92, 21.82, 20.56, 23.16, 21.28, 22.22, 10.88, 23.96, 24.56,
       26.74, 26.3 ,  9.98, 15.74, 23.46, 33.72, 33.46, 15.22, 27.9 ,
       17.2 , 22.76, 22.44, 24.78, 31.62,  9.78, 18.74, 24.38, 23.28,
       28.28, 24.22,

#### Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.


In [15]:
regressor = KNeighborsRegressor(n_neighbors=5,algorithm='auto',weights='distance')
regressor.fit(X_train,y_train)
regressor.predict(X_test)

array([24.53647384, 31.03480478, 15.72056537, 29.59139223, 17.61849361,
       32.02395363, 20.47500086, 15.84360849, 18.4987169 , 20.94911185,
       22.54664945, 20.88348005, 12.23877675, 20.91006945, 23.77262602,
       21.82508719, 20.54223245, 13.77669672, 34.36441456, 10.95866924,
       26.42388876, 30.93258153, 18.67280178, 21.05225726, 17.71262909,
       21.10255918, 22.75749485, 11.94770274, 22.56027537, 20.04157948,
       22.70792905, 23.43559813, 10.25436795, 30.73552035, 18.36319146,
       21.30810832, 22.57223525, 20.41840834, 22.14600095, 30.35916605,
       20.3861741 , 31.25796434, 39.3745921 , 22.27933417, 25.23183002,
       12.3617611 , 18.83902264, 30.19640555, 19.91776014, 22.15870163,
       22.41327114, 34.08078435, 21.68191699, 21.71696862, 30.78169707,
       20.96240258, 12.18981442, 36.59817495, 22.60655322, 20.84712983,
       23.4463727 , 38.38931648, 34.3730875 , 16.1532243 , 30.43729211,
       24.17715971, 11.69290013, 26.54626334, 34.19721654, 12.70

#### Q6. Implement a function to standardise the features before applying KNN classifier.

In [16]:
from sklearn.preprocessing import StandardScaler

def standardize_data(X_train,X_test):
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    return X_train_scaled,X_test_scaled
train_scaled,test_scaled = standardize_data(X_train,X_test)

#### Q7. Write a Python function to calculate the euclidean distance between two points.

In [17]:

import numpy as np

def Euclidian_distance(point1,point2):
    distance = 0
    for i in range(len(point1)):
        distance += (point1[i] - point2[i])**2
    final_distance = np.sqrt(distance)
    return final_distance

pt1 = np.array([2,3])
pt2 = np.array([5,6])
print(Euclidian_distance(pt1,pt2))

4.242640687119285


#### Q8. Write a Python function to calculate the manhattan distance between two points.

In [18]:
def Manhatten_distance(point1,point2):
    distance = 0
    for i in range(len(point1)):
        distance = np.abs(point1[i] - point2[i])
    return distance
pt1 = np.array([4,5])
pt2 = np.array([10,4])
print(Manhatten_distance(pt1,pt2))

1
