##Objective: The objective of this assignment is to gain practical experience with fundamental operations in TensorFlow, including creating and manipulating matrices, performing arithmetic operations on tensors, and understanding the difference between TensorFlow constants and variables.

#Part 1: Theoretical Questions

##1. What are the different data structures used in Tensorflow?. Give some examples.

##Ans:---

###TensorFlow, a popular deep learning framework, provides several data structures for representing and manipulating data. The main data structures used in TensorFlow are:

* Tensor: A tensor is a fundamental data structure in TensorFlow. It is a multi-dimensional array or n-dimensional matrix that represents data. Tensors can be scalars (0-dimensional), vectors (1-dimensional), matrices (2-dimensional), or higher-dimensional arrays. For example, a grayscale image can be represented as a 2D tensor, while a colored image can be represented as a 3D tensor.

* Constant: A constant is a specific type of tensor in TensorFlow that holds a fixed value throughout the execution of a program. The value of a constant cannot be changed once it is defined. Constants are commonly used to store hyperparameters or fixed data.

For example:

In [4]:
import tensorflow as tf

# Creating a constant tensor
x = tf.constant([1, 2, 3])
x


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

##Variable: A variable is another type of tensor in TensorFlow that allows the value to be modified during the execution of a program. Variables are used to represent the trainable parameters of a model, such as weights and biases. For example:

In [3]:
import tensorflow as tf

# Creating a variable tensor
w = tf.Variable([0.5, 1.0])
w


<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([0.5, 1. ], dtype=float32)>

* Placeholder: In earlier versions of TensorFlow, placeholders were used to feed data into the computation graph during training. However, in TensorFlow 2.x, placeholders have been replaced by the tf.data API and the tf.function decorator. Placeholders are no longer required for most use cases and have been deprecated.

* SparseTensor: A sparse tensor is used to efficiently represent tensors with a large number of zero or empty values. It stores only the non-zero elements along with their indices, which helps in reducing memory usage and computational complexity for sparse data.

###These data structures are the building blocks of TensorFlow and are essential for creating and manipulating tensors in TensorFlow programs.

##2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example

##Ans:--

###In TensorFlow, constants and variables are both types of tensors, but they differ in terms of their properties and usage. Here's a comparison between TensorFlow constants and variables:

#TensorFlow Constant:

* A constant in TensorFlow holds a fixed value throughout the execution of a program.

* The value of a constant cannot be changed once it is defined.

* Constants are typically used for storing hyperparameters or fixed data that does not need to be modified during training.

* Constants are immutable and do not support gradient computations for backpropagation.

* Constants can be created using the tf.constant() function.


##Example:

In [5]:
import tensorflow as tf

# Creating a constant tensor
x = tf.constant([1, 2, 3])


#TensorFlow Variable:

* A variable in TensorFlow represents a tensor whose value can be modified during the execution of a program.

* Variables are commonly used to store the trainable parameters of a model, such as weights and biases.

* Variables are mutable and their values can be updated during training using optimization algorithms.

* Variables support gradient computations for backpropagation, allowing automatic differentiation and model optimization.

* Variables can be created using the tf.Variable() function.

##Example:

In [9]:
import tensorflow as tf

# Creating a variable tensor
w = tf.Variable([0.5, 1.0,8.7])


In [10]:

# Printing the values of the constant and variable tensors
print("Constant tensor x:", x.numpy())
print("Variable tensor w:", w.numpy())


Constant tensor x: [1 2 3]
Variable tensor w: [0.5 1.  8.7]


##3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow

##Ans:--


###In TensorFlow, matrix addition, multiplication, and element-wise operations are fundamental operations performed on tensors. Here's a description of each process:

# Matrix Addition:

* Matrix addition is performed by adding corresponding elements of two matrices.

* The matrices involved in the addition operation must have the same shape (same number of rows and columns).

* In TensorFlow, matrix addition is performed using the tf.add() function or the + operator.

* The resulting matrix will have the same shape as the input matrices, and each element will be the sum of the corresponding elements from the input matrices.

##Example:

In [11]:
import tensorflow as tf

# Creating two matrices
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

# Matrix addition
C = tf.add(A, B)

print("Matrix Addition:")
print(C.numpy())


Matrix Addition:
[[ 6  8]
 [10 12]]


#Matrix Multiplication:

* Matrix multiplication is performed by multiplying corresponding elements of rows from the first matrix with the corresponding elements of columns from the second matrix and summing the products.

* The number of columns in the first matrix must be equal to the number of rows in the second matrix for matrix multiplication to be defined.

* In TensorFlow, matrix multiplication is performed using the tf.matmul() function or the @ operator.

* The resulting matrix will have a shape of (number of rows in the first matrix, number of columns in the second matrix).

##Example:

In [12]:
import tensorflow as tf

# Creating two matrices
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

# Matrix multiplication
C = tf.matmul(A, B)

print("Matrix Multiplication:")
print(C.numpy())


Matrix Multiplication:
[[19 22]
 [43 50]]


#Element-wise Operations:

* Element-wise operations are performed by applying an operation to corresponding elements of two tensors.

* The tensors involved in element-wise operations must have the same shape.

* In TensorFlow, element-wise operations are performed using various functions such as tf.add(), tf.subtract(), tf.multiply(), tf.divide(), etc.
* The resulting tensor will have the same shape as the input tensors, and each element will be the result of applying the operation to the corresponding elements from the input tensors.

##Example:

In [14]:
import tensorflow as tf

# Creating two tensors
A = tf.constant([1, 2, 3])
B = tf.constant([4, 5, 6])

# Element-wise addition
C = tf.add(A, B)

# Element-wise multiplication
D = tf.multiply(A, B)

print("Element-wise Addition:")
print(C.numpy())

print("Element-wise Multiplication:")
print(D.numpy())


Element-wise Addition:
[5 7 9]
Element-wise Multiplication:
[ 4 10 18]


#Part 2: Practical Implementation

#Task 1:

##Creating and Manipulating Matrices

###1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the values of matrix A

In [15]:
import tensorflow as tf

# Create a normal matrix A with dimensions 3x3
A = tf.random.normal(shape=(3, 3))

# Display the values of matrix A
print("Matrix A:")
print(A.numpy())


Matrix A:
[[-0.24156626 -2.1190424   1.2473586 ]
 [-0.93316203  0.43400997 -0.09931882]
 [ 0.18687595 -0.31198657 -0.11166593]]


##2. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B

In [16]:
import tensorflow as tf

# Create a Gaussian matrix B with dimensions 4x4
B = tf.random.truncated_normal(shape=(4, 4))

# Display the values of matrix B
print("Matrix B:")
print(B.numpy())


Matrix B:
[[ 0.828068    0.7743483   0.06057705  0.9739507 ]
 [-1.7538556   0.3765717  -0.46541205 -0.6137272 ]
 [ 0.02660602 -0.3484387  -1.6876484  -1.2274835 ]
 [-0.5708102  -1.4714557  -0.2378652   0.19504824]]


###3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.

In [17]:
import tensorflow as tf

# Create a matrix C with dimensions 2x2, drawn from a normal distribution with mean 3 and standard deviation 0.5
C = tf.random.normal(shape=(2, 2), mean=3, stddev=0.5)

# Display the values of matrix C
print("Matrix C:")
print(C.numpy())


Matrix C:
[[2.9495606 3.3371434]
 [2.7315354 3.5545478]]


##4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D

In [20]:
import tensorflow as tf

# Creating matrices A and B
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

# Matrix addition
D = tf.add(A, B)

# Display the values of matrix D
print("Matrix D (Result of Matrix Addition):")
print(D.numpy())


Matrix D (Result of Matrix Addition):
[[ 6  8]
 [10 12]]


###5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E



In [21]:
import tensorflow as tf

# Creating matrices C and D
C = tf.constant([[3, 4], [5, 6]])
D = tf.constant([[1, 2], [3, 4]])

# Matrix multiplication
E = tf.matmul(C, D)

# Display the values of matrix E
print("Matrix E (Result of Matrix Multiplication):")
print(E.numpy())


Matrix E (Result of Matrix Multiplication):
[[15 22]
 [23 34]]


#Task 2:

##Performing Additional Matrix Operations

###1. Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random_uniform function.

In [22]:
import tensorflow as tf

# Create a matrix F with dimensions 3x3, initialized with random values
F = tf.random.uniform(shape=(3, 3))

# Display the values of matrix F
print("Matrix F:")
print(F.numpy())


Matrix F:
[[0.12378407 0.03413093 0.73716867]
 [0.50875854 0.20093203 0.5039369 ]
 [0.44111085 0.4537933  0.1841408 ]]


###2. Calculate the transpose of matrix F and store the result in matrix G.


In [23]:
import tensorflow as tf

# Creating matrix F
F = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculating the transpose of matrix F
G = tf.transpose(F)

# Display the values of matrix G
print("Matrix G (Transpose of Matrix F):")
print(G.numpy())


Matrix G (Transpose of Matrix F):
[[1 4 7]
 [2 5 8]
 [3 6 9]]


###3. Calculate the element-wise exponential of matrix F and store the result in matrix H.

In [25]:
import tensorflow as tf


F = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=tf.float32)

# Calculating the element-wise exponential of matrix F
H = tf.exp(F)

# Display the values of matrix H
print("Matrix H (Element-wise Exponential of Matrix F):")
print(H.numpy())


Matrix H (Element-wise Exponential of Matrix F):
[[2.7182817e+00 7.3890562e+00 2.0085537e+01]
 [5.4598148e+01 1.4841316e+02 4.0342877e+02]
 [1.0966332e+03 2.9809580e+03 8.1030840e+03]]


###4. Create a matrix I by concatenating matrix F and matrix G horizontally.

In [27]:
import tensorflow as tf

# Concatenating matrices F and G horizontally
I = tf.concat([F, G], axis=1)

# Display the values of matrix I
print("Matrix I (Concatenation of F and G Horizontally):")
print(I.numpy())


Matrix I (Concatenation of F and G Horizontally):
[[1 2 3 1 4 7]
 [4 5 6 2 5 8]
 [7 8 9 3 6 9]]


###5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [30]:
import tensorflow as tf

# Creating matrices F and H
F = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=tf.float32)
H = tf.constant([[2.7182817, 7.389056, 20.085537],
                 [54.59815, 148.41316, 403.4288],
                 [1096.6332, 2980.958, 8103.0835]])

# Concatenating matrices F and H vertically
J = tf.concat([F, H], axis=0)

# Display the values of matrix J
print("Matrix J (Concatenation of F and H Vertically):")
print(J.numpy())


Matrix J (Concatenation of F and H Vertically):
[[1.0000000e+00 2.0000000e+00 3.0000000e+00]
 [4.0000000e+00 5.0000000e+00 6.0000000e+00]
 [7.0000000e+00 8.0000000e+00 9.0000000e+00]
 [2.7182817e+00 7.3890562e+00 2.0085537e+01]
 [5.4598148e+01 1.4841316e+02 4.0342880e+02]
 [1.0966332e+03 2.9809580e+03 8.1030835e+03]]
